{% set name = "omsl" %}
{% set mslversion = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ mslversion }}

source:
  url: https://github.com/OpenModelica/OpenModelica-ModelicaStandardLibrary/archive/c11123102e94d4b5acb139331a6d85f45d8adcc0.zip
  sha256: 0792c4841a0ab8e2ffb750a0a1fffa45d6a5b6b224c045db67c241fef570c229

build:
  skip: true  # [not linux]
  script_env:
   - MSLVERSION={{ mslversion }}
  number: 0

test:
  requires:
    - python >=3.9
    - omcompiler

about:
  home: https://github.com/OpenModelica/OpenModelica-ModelicaStandardLibrary
  summary: 'OpenModelica Patched Version of the Modelica Standard Library'
  description: |
    The package Modelica is a free library that is developed together with
    the Modelica language from the Modelica Association. It is also called
    Modelica Standard Library. It provides model components and standard
    component interfaces from many engineering domains. Each model comes
    with documentation included.
    OpenModelica <https://openmodelica.org> is a Modelica simulation
    environment. It is required for the usage of this library and is provided
    by the conda package omcompiler.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - joewa
